# Generated by Django 5.2 on 2025-04-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAndDock', '0002_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='category',
            field=models.CharField(choices=[('guide', 'Guide'), ('article', 'Article')], default='guide', max_length=10),
        ),
    ]
