# Generated by Django 5.2 on 2025-04-28 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAndDock', '0004_dock'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('length', models.FloatField(help_text='Length of the dock space (in meters)')),
                ('width', models.FloatField(help_text='Width of the dock space (in meters)')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='BookAndDock.dock')),
            ],
        ),
    ]
